variables:
    GIT_SUBMODULE_STRATEGY: recursive
    # Disable the Gradle daemon for Continuous Integration servers as correctness
    # is usually a priority over speed in CI environments. Using a fresh
    # runtime for each build is more reliable since the runtime is completely
    # isolated from any previous builds.
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"


# Cache downloaded dependencies and plugins between builds
# and use our global maven cache 'one-maven-cache-to-rule-them-all'
cache:
    key: one-parsx-cache-to-rule-them-all
    untracked: false
    paths:
        - .m2/repository
        - .gradle/


stages:
    - prepare next development cycle
    - deploy
    - release


.gradle_template:
    image: gradle:8.4-jdk21-jammy
    rules:
        # not in tags
        -   if: $CI_COMMIT_TAG == null
    before_script:
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - mkdir -p $GRADLE_USER_HOME || true
        - cp .gitlab-ci/artifactory-access/init.gradle $GRADLE_USER_HOME


deploy:registry:gitlab:
    extends: .gradle_template
    stage: deploy
    rules:
        # only if a branch is defined, i. e. not on tags.
        -   if: $CI_COMMIT_BRANCH
    script:
        - ./gradlew publish


deploy:registry:gradlePluginPortal:
    extends: .gradle_template
    stage: deploy
    rules:
        -   if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    script:
        - ./gradlew publishPlugins


git:release:
    extends: .gradle_template
    stage: release
    rules:
        -   if: '$CI_COMMIT_BRANCH == "development"'
            when: manual
    script:
        # Create a new commit on the main branch
        - ./gradlew configureReleaseBot
            switchToMainAndCatchItUp
            removeSnapshotFromVersion
            updateVersionNumberInReadme
            gitCommitForRelease
            createGitTagForVersion
            gitPush


git:preparesnapshot:
    extends: .gradle_template
    stage: prepare next development cycle
    rules:
        -   if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    script:
        # Only perform the branching when this is not a SNAPSHOT version on the main branch.
        - if [[ ($(./gradlew properties | grep version) =~ "SNAPSHOT") ]]; then exit 0; fi
        # Create a new commit on the development branch for the next version
        - ./gradlew configureReleaseBot
            switchToDevelopmentAndCatchItUp
            prepareNextSnapshotVersion
            updateVersionNumberInReadme
            gitCommitForSnapshot
            gitPush
