package gmbh.pagina.tools.gradle;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ResourceBundle;

/**
 * Runtime utility that exposes the build-time metadata written into {@code meta.properties} by the
 * {@code createProperties} Gradle task.
 *
 * <p>Apply the {@code gmbh.pagina.tools.gradle.app-properties} plugin in your build — the {@code
 * app-properties-lib} jar (containing this class) is added to your {@code implementation} classpath
 * automatically, so no extra dependency declaration is needed.
 *
 * <p>All fields are {@code public static final} and are initialised once when the class is first
 * loaded. Configure the values via the {@code appProperties} extension in your build script:
 *
 * <pre>{@code
 * appProperties {
 *     displayName       = "My Application"        // optional, default: project.name
 *     copyrightHolder   = "pagina GmbH, Tübingen" // optional, default: "" (omitted)
 *     copyrightFromYear = 2020                    // optional, default: absent (build year only)
 * }
 * }</pre>
 *
 * @author Hans Schülein
 * @see <a href="https://github.com/paginagmbh/app-properties">app-properties on GitHub</a>
 */
public final class AppProperties {

    // ===============================================================================================
    // Property Interface
    // ===============================================================================================

    /** The metadata properties file generated by the {@code createProperties} task. */
    private static final ResourceBundle meta = ResourceBundle.getBundle("meta");

    /**
     * The application's build version, taken directly from {@code project.version} at build time.
     *
     * <p>Example value: {@code "1.2.0"} or {@code "1.2.0-SNAPSHOT"}.
     */
    public static final String version = meta.getString("version");

    /**
     * The application's display name, set via the {@code displayName} extension property.
     *
     * <p>Falls back to the Gradle project name when {@code displayName} is not configured.
     *
     * <p>Example value: {@code "My Application"}.
     */
    public static final String name = meta.getString("name");

    /**
     * The date on which this artifact was built, parsed from the ISO-8601 string stored in {@code
     * meta.properties}.
     *
     * <p>Use {@link #isoBuildDate} for a pre-formatted string representation, or call {@code
     * buildDate.format(DateTimeFormatter.ofPattern(…))} for a custom format.
     *
     * <p>Example value: {@code 2026-03-31} (as a {@link java.time.LocalDate}).
     */
    public static final LocalDate buildDate = LocalDate.parse(meta.getString("buildDate"));

    /**
     * The build date pre-formatted as an ISO-8601 date string ({@code yyyy-MM-dd}).
     *
     * <p>Convenience alternative to calling {@code buildDate.toString()}.
     *
     * <p>Example value: {@code "2026-03-31"}.
     */
    public static final String isoBuildDate = buildDate.format(DateTimeFormatter.ISO_LOCAL_DATE);

    /**
     * The copyright holder, set via the {@code copyrightHolder} extension property.
     *
     * <p>Returns an empty string when {@code copyrightHolder} was not configured, in which case
     * {@link #copyrightString} and the copyright portion of {@link #versionDescriptor} are also
     * empty.
     *
     * <p>Example value: {@code "pagina GmbH, Tübingen"} or {@code ""}.
     */
    public static final String copyrightHolder = meta.getString("copyrightHolder");

    /**
     * The optional first year of the copyright range, set via the {@code copyrightFromYear}
     * extension property.
     *
     * <p>Returns an empty string when {@code copyrightFromYear} was not configured. When non-empty
     * and earlier than the build year, {@link #copyrightString} will contain a year range (e.g.
     * {@code "© 2020-2026 …"}).
     *
     * <p>Example value: {@code "2020"} or {@code ""}.
     */
    public static final String copyrightFromYear = meta.getString("copyrightFromYear");

    /**
     * The full copyright notice, spanning from the © symbol to the end of the holder string.
     *
     * <p>The year portion is determined as follows:
     *
     * <ul>
     *   <li>If {@link #copyrightFromYear} is set and earlier than the build year, a range is used:
     *       {@code "© 2020-2026 pagina GmbH, Tübingen"}.
     *   <li>Otherwise only the build year is shown: {@code "© 2026 pagina GmbH, Tübingen"}.
     *   <li>If {@link #copyrightHolder} is empty, this field is {@code ""}.
     * </ul>
     */
    public static final String copyrightString =
            copyrightHolder.isEmpty()
                    ? ""
                    : "© " + buildCopyrightYearRange() + " " + copyrightHolder;

    /**
     * A human-readable version descriptor combining the most important build metadata into a single
     * string suitable for log output, about dialogs, or CLI version flags.
     *
     * <p>Format: {@code "<name> <version>, built <buildDate> <copyrightString>"}, where the
     * copyright portion is omitted when {@link #copyrightHolder} is empty.
     *
     * <p>Example values:
     *
     * <ul>
     *   <li>{@code "My Application 1.2.0, built 2026-03-31 © 2020-2026 pagina GmbH, Tübingen"}
     *   <li>{@code "My Application 1.2.0, built 2026-03-31"} (no copyright configured)
     * </ul>
     */
    public static final String versionDescriptor =
            name
                    + " "
                    + version
                    + ", built "
                    + buildDate
                    + (copyrightString.isEmpty() ? "" : " " + copyrightString);

    // Private constructor — static utility class
    private AppProperties() {}

    // ===============================================================================================
    // Helpers
    // ===============================================================================================

    /**
     * Builds the year (or year range) portion of the copyright string.
     *
     * <p>Returns {@code "<fromYear>-<buildYear>"} when {@link #copyrightFromYear} is non-empty and
     * strictly less than the build year; otherwise returns {@code "<buildYear>"} as a plain string.
     */
    private static String buildCopyrightYearRange() {
        int buildYear = buildDate.getYear();
        if (!copyrightFromYear.isEmpty()) {
            int fromYear = Integer.parseInt(copyrightFromYear);
            if (fromYear < buildYear) {
                return fromYear + "–" + buildYear;
            }
        }
        return String.valueOf(buildYear);
    }
}
